### PR TITLE
remotion.dev/convert: Allow to use it offline 

### PR DESCRIPTION
**Pull request by Myestery**
fix https://github.com/remotion-dev/remotion/issues/4607
/claim #4607

### CODE REVIEW

**Comment by Myestery** [comment]
Hi @JonnyBurger 

I am almost done here, just the failing vercel build. I'll like to get logs for those if possible.
I had to touch the auto-select-writer file cos WebFs didn't work well on offline mode however the PWA works as expected using the Buffer fallback.

**Comment by JonnyBurger** [comment]
Looking very nice so far!

These are the logs:

image


I don't know why that is but if you struggle, leave it, we'll take care of resolving it.

**Comment by Myestery** [comment]
> Looking very nice so far!
> 
> These are the logs:
> 
> image
> 
> I don't know why that is but if you struggle, leave it, we'll take care of resolving it.

okay, I'm a bit confused on how to replicate or fix this one so I'll need some help if its required to close the bounty

**Comment by JonnyBurger** [comment]
Awesome! 

Thanks a lot, this is great 🤩

**Review by JonnyBurger — APPROVED** [review]

**Comment by Myestery** [comment]
@JonnyBurger I noticed you moved the service worker to stay under /convert, I had issues with this approach cos the scope would then be /convert/* which excludes the /convert page itself.
So it didn't load offline

**Comment by JonnyBurger** [comment]
It does seem to work for me, but I will revisit this when it is deployed, thank you!

image

**Comment by Myestery** [comment]
Hi @JonnyBurger 
Thanks for merging this, however the app still doesnt work without internet due to the issue I raised with the placement of the js file.
Most of the requests are supposed to be intercepted by the service worker but they are not

**Comment by JonnyBurger** [comment]
thanks a lot for watching my fingers!

Trying to quick-fix it with 379f121ecfb673ecebaf9b866998defc860d093b

**Pull request merged**
