### PR TITLE
chore: create font-display: swap issue demo

### PR DESCRIPTION
**Pull request by arthurdenner**
Relates to [this comment](https://github.com/remotion-dev/remotion/issues/317#issuecomment-871690225).

## Steps to reproduce

- Clone this branch (arthurdenner:feat/wait-for-fonts)
- Run `npm run build -- --watch` in the `packages/renderer` folder
- Run `npm run render` in the `packages/example` folder

This will (hopefully) give you a video with a delayed font swapping, like the one below.
PS: You may need to run the `render` two times - maybe some cache in the build process?

<details><summary>Video</summary>

https://user-images.githubusercontent.com/13774309/124334814-9702ff00-db98-11eb-8a41-f64a572332a2.mp4

</details>

- Uncomment the `await page.evaluateHandle('document.fonts.ready');` line ([ref](https://github.com/arthurdenner/remotion/blob/feat/wait-for-fonts/packages/renderer/src/render.ts#L131));
- Verify the `npm run build -- --watch` output was updated just in case
- Run `npm run render` in the `packages/example` folder

This will (hopefully) give you a video *without* a delayed font swapping, like the one below, because we postpone rendering frames until fonts are ready.
PS: You may need to run the `render` two times - maybe some cache in the build process?

<details><summary>Video</summary>

https://user-images.githubusercontent.com/13774309/124334972-0e389300-db99-11eb-840e-f4cdf3696d0e.mp4

</details>

You can comment and uncomment the `await page.evaluateHandle('document.fonts.ready');` line a few times.
I was able to reproduce the bug and verify the proposed fix many times but sometimes I had to `npm run render` twice as mentioned above.

### CODE REVIEW

**Comment by JonnyBurger** [comment]
This is great! I had no idea about this API. Absolutely perfect. 

Also I found this by coincidence: https://github.blog/2021-06-22-framework-building-open-graph-images/

Shows how to correctly await document.fonts.ready

**Comment by JonnyBurger** [comment]
@arthurdenner @sashee I pushed a commit that I think solves the problem: [`3189a90` (#486)](https://github.com/remotion-dev/remotion/pull/486/commits/3189a9056fb8e977f68a1139a1069607ac170658)

Do you want to take a look?

**Comment by arthurdenner** [comment]
@JonnyBurger, have you tried the steps in this PR?

Only `await page.evaluateHandle('document.fonts.ready');` solves the issue I think. Maybe it wasn't clear but I only left the line commented in this PR so you could uncomment while going through the steps to verify the fix yourselves 😅 

Hook up the same API into Remotion internals seems like a valid option too, you definitely know better where the usage of the API is more secure/stable/whatever 😄

**Comment by JonnyBurger** [comment]
@arthurdenner Hmm, ok I'm trying to understand it. So basically I created the same solution but it's not fully reliably and it gets stuck sometimes? 

Or is there no issue at all and this PR proposes a fix to be merged?

**Comment by JonnyBurger** [comment]
By the way, I ran the render 100 times via a bash loop and it worked well, no getting stuck and it always waited for the font! Looking good

**Comment by arthurdenner** [comment]
The changes you did seem to do the same effect as just `await page.evaluateHandle('document.fonts.ready');` does.

This PR is just a `chore` and not a `fix` because it contains more changes to build a reproducible scenario using one of the examples.
The purpose was to follow the steps in the description so you could verify `await page.evaluateHandle('document.fonts.ready');` works.

If we verify that it works fine (because there may be edge cases or other relevant parts of the codebase I'm not aware of), then I'd open a proper PR to fix it.

**Comment by JonnyBurger** [comment]
Thanks for explaining! And sorry for getting lost and not understanding correctly, was indeed quickly switching between various issues 😌

In that case, I would suggest we just add that one line of code and merge it, what do you say? Just did a test and seemed reliable.

**Comment by arthurdenner** [comment]
No worries, I know there is a lot going on in the repo and maybe I wrote too much text to explain this. 😆 

It's great that you could validate that change. Can I open a PR with that line only and if we find any issues, we can try your changes?

**Comment by JonnyBurger** [comment]
Sounds good! Thanks a lot :)

**Comment by arthurdenner** [comment]
Closing this in favor of #501.

**Pull request closed without merging**
