### PR TITLE
Add `<Credits>` component to shout out contributors

### LINKED ISSUE #3001: Implement a "credits" component for the documentation
Many people have contributed to the Remotion docs, but we do not have a nice way to give credits.  
The goal is to make a new component for which we can display the profile picture and name.

**Mockup**:

image

## Acceptance criteria

- Create a new JSX component `<Credits>` in this file: https://github.com/remotion-dev/remotion/blob/50b1424eb14cc62cb805834bf63ee7901e56975c/packages/docs/src/theme/MDXComponents.js
- Make a component which can display one or multiple authors
- Each author can be clicked on to go to GitHub, has a picture (`https://github.com/[username].png`) and a subtitle specifying the type of contribution.
- On mobile, it should look good as well.
- Add the `<Credits>` component to different pages, highlighting at least 10 different contributors. You don't need to import the component to be available in markdown. You can for example look up previous Hacktoberfest contributions: https://github.com/remotion-dev/remotion/issues?q=is%3Aissue+sort%3Aupdated-desc+label%3A%22%F0%9F%A5%A8++hacktoberfest%22+is%3Aclosed

## Bounty
💎 This issue is part of Hacktoberfest and has a bounty on it!
- **General Rules**: https://www.remotion.dev/bounties
- **How to contribute**: https://www.remotion.dev/docs/contributing/
- **Implementing a new feature**: https://www.remotion.dev/docs/contributing/feature
- **Implementing a new option**: https://www.remotion.dev/docs/contributing/option
- **Write documentation**: https://www.remotion.dev/docs/contributing/docs (this one is helpful here)

🎃 **Hacktoberfest rules**
- You can only work on 1 issue at a time.
- Only 1 person can work on the same issue.
- We explicitly assign a developer. Don’t work on an issue if we do not assign you.
- First-time contributors will get preferential treatment.
- You must set up the Remotion repository locally and test your changes. [Contributing to Remotion](https://www.remotion.dev/docs/contributing)
- Your PR must fulfill the acceptance criteria.
- If you use AI, you must verify that the output is correct.
- All tests (functionality and formatting) must pass.

Issue already taken? Find more issues under https://remotion.dev/bounties

/bounty 200

### PR DESCRIPTION
**Pull request by evoxf1**
## Pull Request Description

This pull request addresses issue #3001.

### Changes Made

I added a new `Credit` component to the project. This component accepts props to display contributors' information, including their photo, GitHub profile link, and the contribution they made to the project.

### Related Issues

- Fixes #3001

### Test Suite

I have tested the `Credit` component with various props to ensure it displays contributors' information correctly. The existing test suite passes after the addition of this component.

### Potential Tradeoffs

No significant tradeoffs were made during the implementation of this feature. The component is designed to be flexible and easy to use, allowing project contributors to showcase their information easily.

## Checklist

- [x] I have read the CONTRIBUTING.md file.
- [x] I have linked the relevant issue(s) (#3001).
- [x] I have made an effort to make the test suite pass.
- [ ] I have documented potential tradeoffs in this PR. (if applicable)

### CODE REVIEW

**Comment by IamSAL** [comment]
On dark mode, name stays black. it should be something lighter/white instead.


image

**Comment by evoxf1** [comment]
Oh shoot. I didnt even thought of that, thanks. Will fix it rightaway.

**Comment by evoxf1** [comment]
> On dark mode, name stays black. it should be something lighter/white instead.
> 
> image

Untitled

**Comment by evoxf1** [comment]
Untitled

tried something please do check, also @IamSAL thanks for the feedback you are awesome for pointing it out, I was completely unaware of the same.

**Review by JonnyBurger — APPROVED** [review]
Thanks! 🙌

**Comment by evoxf1** [comment]
> Thanks! 🙌

Anytime. 🙌

**Pull request merged**
