### PR TITLE
Php client

### PR DESCRIPTION
**Pull request by alexfernandez803**
A PHP Client for Remotion

### CODE REVIEW

**Comment by alexfernandez803** [comment]
@JonnyBurger  shall I override this article(https://www.remotion.dev/docs/lambda/php) for the writeup of this client?

**Comment by JonnyBurger** [comment]
@alexfernandez803 Yes, you can override it! 🫡

**Comment by JonnyBurger** [comment]
@alexfernandez803 Can you get the tests to run in CI?
WIll review as soon as it's green or you say you're done!

**Comment by alexfernandez803** [comment]
> @alexfernandez803 Can you get the tests to run in CI? WIll review as soon as it's green or you say you're done!

@JonnyBurger  sure will do. I'll check which setup is appropriate for PHP in github actions.

**Comment by JonnyBurger** [comment]
Thanks! Will review shortly 🫡

**Pull request merged**
