### PR TITLE
Player  `onTimeUpdate` callback on time update.

### LINKED ISSUE #429: Player `timeupdate` event
[Issuehunt badges](https://issuehunt.io/r/JonnyBurger/remotion/issues/429)

Analogue to the HTML5 event, occasionally send events as the video progresses.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $60.00)

- [jonnyburger jonnyburger](https://issuehunt.io/u/jonnyburger) ($60.00)

### Submitted pull Requests
- [#492 Player  `onTimeUpdate` callback on time update.](https://issuehunt.io/r/JonnyBurger/remotion/pull/492)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/JonnyBurger/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

### PR DESCRIPTION
**Pull request by ashikmeerankutty**
- Adding a callback containing elapsed time in analogue to he HTML5 `timeupdate` event

Fixes #429 

Screen Cast 2021-07-06 at 10 43 22 PM

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#429: Player `timeupdate` event](https://issuehunt.io/repos/274495425/issues/429)
---
</details>

### CODE REVIEW

**Comment by JonnyBurger** [comment]
Thanks a lot for working on this! 🔥  Appreciate it a lot.

It looks good to me from a functionality standpoint, but   I'd suggest a few changes:

- The HTML5 event is not a prop, but it's an event. Can we make it an event instead?
 `onTimeUpdate={() => {}}` --> `ref.addEventListener('timeupdate')`

We already have an event system, see for example the `seeked` event.

- We should throttle it a bit, I think the HTML5 `timeupdate` event only fires every 250ms to prevent a lot of code being executed and the page becoming slow.


Finally, can you run Prettier `npx prettier src --write` in the player package to format the code?

Let me know if you have any questions!

Re: bounty, we heard from people that they can only withdraw from IssueHunt if they have at least $100 to be paid out. If you would like to receive it over PayPal or Crypto instead, you can let me know.

**Comment by ashikmeerankutty** [comment]
@JonnyBurger  Thanks for the quick response. I changed the callback prop to `timeupdate` event and throttled it for `250ms`. 
Also formatted the code using prettier. Please do review and let me know if anything is missing.

**Comment by JonnyBurger** [comment]
@ashikmeerankutty Thanks a lot for the swift changes! I will get to review it tomorrow.

**Comment by JonnyBurger** [comment]
Thanks a lot! Looks very good. I added some documentation and moved the event trigger in another location so the remotion preview can also benefit from it.

Let's ship it! 🙌 💙

**Review by JonnyBurger — APPROVED** [review]

**Comment by ashikmeerankutty** [comment]
@JonnyBurger  Cool, Looks like you have done a lot of changes 😅 . Lets ship 🚀

**Pull request merged**
