### PR TITLE
chore: upgrade jest to version 28

### PR DESCRIPTION
**Pull request by Slashgear**
## Why

Last week jest published the 28 version.
In order to keep remotion up to date, here is a PR that is passing all the breaking changes.

## How

- update jest to 28
- update types/jest to latest
- update ts-jest to 28 (needed for jest 28 compatibility)
- add `jest-environnement-node`, `jest-environnement-jsdom` as they are not natively included in jest

## Ressources

- [Jest blog 28 post](https://jestjs.io/fr/blog/2022/04/25/jest-28)
- [`ts-jest` last release](https://github.com/kulshekhar/ts-jest/releases/tag/v28.0.0)

### CODE REVIEW

**Comment by JonnyBurger** [comment]
Thanks a lot! 🙌 Tests seem to fail in ESLint plugin.
Needs to be investigated still... either by you or me, whenever we find time 😃

**Comment by Slashgear** [comment]
@JonnyBurger I will take a look at it, I had some issues with pnpm lock compared to master.
I am on it :)

**Comment by Slashgear** [comment]
@JonnyBurger I quickly took a look locally and I can't really understand what is happening here.

Locally test about `eslint-plugin` are passing but the one from `it-tests` fails 🤔

**Comment by JonnyBurger** [comment]
I'm going to close it because in the meanwhile we migrated some packages to vitest and I see the future more in that!
Thanks nonetheless for the PR, which I greatly appreciated!

**Pull request closed without merging**
