### PR TITLE
`@remotion/cli`: Split up `setPort()` into `setStudioPort()` and `setRendererPort()`

### LINKED ISSUE #3008: Split up `setPort()` option
Currrently the `Config.setPort()` option sets the port for the Remotion Studio but also for rendering.
Now that you render from within the studio that leads to a conflict.

We should split it up to `Config.setStudioPort()` and `Config.setRendererPort()`. `Config.setPort()` should get a `@deprecated` JSDoc command but for now set both ports still.

The `--port` flag should set the Studio port when running the `remotion studio` command, but the renderer port when using any other  command.

### PR DESCRIPTION
**Pull request by jkcs**
Close #3008 
/claim #3008

### CODE REVIEW

**Comment by jkcs** [comment]
Why did everything fail? Do I need to merge the code from master?

**Comment by JonnyBurger** [comment]
Thanks for the PR!

It is because `initializeCli ` is also being used in the packages/lambda package, and there it is now missing one argument.

**Comment by JonnyBurger** [comment]
Thanks a lot for the PR! Should be able to review it in 1-2 days.

**Comment by JonnyBurger** [comment]
Thanks a lot for the lovely PR! I am retroactively adding a bounty on it since we promised we give back more to the community in October 🙂

**Comment by jkcs** [comment]
> Thanks a lot for the lovely PR! I am retroactively adding a bounty on it since we promised we give back more to the community in October 🙂

@JonnyBurger Thank you very much.

**Pull request merged**
