### PR TITLE
Add Showcase route to website

### PR DESCRIPTION
**Pull request by kave-me**

### CODE REVIEW

**Comment by JonnyBurger** [comment]
Hey @kave-me! This is amazing! Thanks a lot for kicking this off.
I just worked a bit on it myself and implemented an Instagram-style popup player when you click on it, so you can see the video in higher resolution.

As the next steps, we need to add more videos. @Iamshankhadeep can you add the ones you have already researched?

Also, I thought it's not very scalable to keep all videos in the git repo. Therefore I created a [Mux](https://mux.com) account where we can upload videos and get a HLS link in return (with HLS you get a lower quality video when you have less bandwidth which is good).

So when somebody submits to the showcase, the idea is that either me or @Iamshankhadeep upload the video to Mux instead, replace the link and merge using the *squash* strategy, to remove the video from git history.

Before we announce it, some UI tweaks that I would find nice:

- square thumbnails instead of widescreen ones?
- fill the thumbnails instead of black bars
- show the submitter name
- previous / back button
- better responsive support

I'll work on this too, after I release Remotion 2.0 which is my priority right now.

**Comment by JonnyBurger** [comment]
Also feel free to try to post more videos we should add to the showcase here!

- **"The X in MDX" talk** [Watch](https://twitter.com/pomber/status/1359556846688886789) • [Source code](https://github.com/pomber/record-talk-with-remotion) • A re-recording of [this talk](https://www.youtube.com/watch?v=xEu3t-KJVVg) using Remotion.
- **Redesigning the Scatterplot** [Watch](https://twitter.com/BrooksLybrand/status/1371547875109445635) • [Source code](https://github.com/brookslybrand/redesigning-scatterplots) • An animated section of Edward R. Tufte's book [The Visual Display of Quantitative Information](https://www.amazon.com/Visual-Display-Quantitative-Information/dp/0961392142/ref=sr_1_1?crid=3HQZSBUUROV09&dchild=1&keywords=the+visual+display+of+quantitative+information&qid=1615907320&sprefix=the+visual+disp%2Caps%2C190&sr=8-1).

- https://twitter.com/matfrana/status/1372336451246034948
- https://twitter.com/FlorentPergoud/status/1371874105281159178
- https://twitter.com/Iamshankhadeep/status/1370764956019220480
- https://twitter.com/vjo/status/1367901005027942403
- https://twitter.com/quantargo/status/1365233907793338369
- https://twitter.com/FanaHOVA/status/1362507530476347400
- https://twitter.com/SamLarsenDisney/status/1362029962241466372
- https://twitter.com/zackdotcomputer/status/1360682974224744452
- https://twitter.com/AmineJv/status/1359964006371500032

> Hey Jonny,
> I saw that you are collecting links to videos made with Remotion
( [https://github.com/JonnyBurger/remotion#example-videos](https://github.com/JonnyBurger/remotion#example-videos) ). I recently
finished a new intro for one of my courses using Remotion, so you
might be interested in adding it to the list.
> The video is here (you can download it if it doesn’t play):
 [https://drive.google.com/file/d/1lkKZRBl3l1iJccVUwRbBn2eMroARPQvH/view?usp=sharing](https://drive.google.com/file/d/1lkKZRBl3l1iJccVUwRbBn2eMroARPQvH/view?usp=sharing) 
> And the course is:
 [https://www.udemy.com/course/the-cloud-architects-guide-to-cloudfront/?referralCode=1643F751D44572FA0E42](https://www.udemy.com/course/the-cloud-architects-guide-to-cloudfront/?referralCode=1643F751D44572FA0E42) 

- https://discord.com/channels/809501355504959528/817306292590215181/822094164501201016
- https://github.com/florentpergoud/vfb-crowdfunding-campain

and all the other ones from Discord #showcase channel

**Comment by JonnyBurger** [comment]
Almost there! Remaining TODOs:

- [ ] Add remaining submissions
- [ ] Proofread existing ones
- [ ] X button on top right of the backdrop
- [ ] full width mobile responsive design in feed
- [ ] shuffle videos on modile
- [ ] Add creator name and link
- [ ] click to pause
- [ ] catch autoplay failure when opening permalink
- [ ] update showcase uploader with new field format
- [ ] update og:image on showcase uploader

**Comment by JonnyBurger** [comment]
Although not all videos have been added, I think it's ready to merge! You wanna review it @Iamshankhadeep ?

**Review by Iamshankhadeep — APPROVED** [review]
wow. Works great good to merge. :fire:

**Pull request merged**
