### PR TITLE
accelerated video example

### PR DESCRIPTION
**Pull request by kaf-lamed-beyt**
Hi @JonnyBurger,

Kindly take a look at this draft of the doc that I've prepared, and let me know how I can improve on it.

I'm still trying to figure out how to make the video example via the `<Player />` component interactive, in such a way that'll allow people to able to dynamically set the playback speed or so.

### CODE REVIEW

**Comment by kaf-lamed-beyt** [comment]
Hi @JonnyBurger, Is there anything that you'd love me to improve on?

**Comment by JonnyBurger** [comment]
Hey @kaf-lamed-beyt, not for now, I did not find time yet to review it! Trying tomorrow 🙂

**Comment by kaf-lamed-beyt** [comment]
Alright then.

I'll be expecting your review 😎

**Comment by JonnyBurger** [comment]
Thanks a lot, looks good!

I changed some things such as removing irrelevant language (tweaking parameters even though there are none), and fixed a syntax error and broke it down to a minimal example.

I also realized that it can not just be used for accelerating, but also for decelerating videos, so I changed the title.

Appreciate the PR a lot! 🙌

**Comment by kaf-lamed-beyt** [comment]
Thank you for the feedback @JonnyBurger, I'll keep improving 😄

**Pull request merged**
