### PR TITLE
chore(docs): update bounce and beizer with clear signatures

### LINKED ISSUE #2973: Easing docs are confusing
image

You can call Easing.bezier yourself, but not Easing.bounce, but they look equivalent in the docs

### PR DESCRIPTION
**Pull request by kaf-lamed-beyt**
@JonnyBurger how does this look?

fixes #2973

### CODE REVIEW

**Comment by JonnyBurger** [comment]
@kaf-lamed-beyt Thanks a lot! 
Yes, not bad, can you also update the signatures for all the other easings available? No need to further explain it, I think that would already be super helpful

**Comment by kaf-lamed-beyt** [comment]
Awesome!! 🚀

Thanks for the feedback @JonnyBurger. I'll let you know when I'm done.

**Comment by kaf-lamed-beyt** [comment]
@JonnyBurger, please check it out and let me know if it looks okay.

**Comment by JonnyBurger** [comment]
@kaf-lamed-beyt Almost, the documentation should match the actual function signatures at https://github.com/remotion-dev/remotion/blob/4e765c61037f158bcdc03a7683f51cec231e681a/packages/core/src/easing.ts.

Fixed it now! If you want a React Native contribution, feel free to send the same changes also to https://reactnative.dev/docs/easing

**Review by JonnyBurger — APPROVED** [review]

**Comment by kaf-lamed-beyt** [comment]
Ah! I see. 

Thank you so much, @JonnyBurger! I'll go ahead and send a PR to the RN docs.

**Pull request merged**
