### PR TITLE
feat(4342): add metadata field to renderMedia(), renderMediaOnLambda() and renderMediaOnCloudRun()

### LINKED ISSUE #4342: `metadata` field for `renderMedia()`, `renderMediaOnLambda()` and `renderMediaOnCloudRun()` API
I would like to request a feature that enables the modification of EXIF data, such as the "Comment" and "Author" fields, after a video has been rendered via AWS Lambda.

### PR DESCRIPTION
**Pull request by akhilender-bongirwar**
Fixes #4342 
/claim #4342 

### Overview
This pull request introduces a mandatory `metadata` field to the `renderMedia()`, `renderMediaOnLambda()`, and `renderMediaOnCloudRun()` APIs. This enhancement allows users to include essential metadata for their rendered videos, enriching the output with context and additional information.

### CODE REVIEW

**Comment by akhilender-bongirwar** [comment]
@JonnyBurger, as discussed in the issue description, I have successfully implemented the `metadata field` and resolved all associated errors by running `pnpm watch` command.

While I am aware that there are still additional documentation updates to be made, I wanted to confirm whether I am on the right track in resolving this issue.

**Comment by JonnyBurger** [comment]
You are on the right track!

It should be an optional field, so that people can upgrade without making any changes to their code.

This leads to the CI failure I believe.

**Comment by akhilender-bongirwar** [comment]
> You are on the right track!
> 
> It should be an optional field, so that people can upgrade without making any changes to their code.
> 
> This leads to the CI failure I believe.

Ohh, so should I make all the `metadata` fields `optional`?

**Review by JonnyBurger — APPROVED** [review]

**Review by JonnyBurger — APPROVED** [review]

**Comment by JonnyBurger** [comment]
Nice job! 🙌

**Review by JonnyBurger — DISMISSED** [review]

**Comment by akhilender-bongirwar** [comment]
> Nice job! 🙌

Thank you for the support 🙏😊

**Pull request merged**
