### PR TITLE
Warn if Bun cannot determine musl or glibc and assume glibc

### LINKED ISSUE #3062: renderMedia fails on Bun
When using renderMedia to ssr render a composition with bun, it fails returning the following error.

**TypeError: undefined is not an object (evaluating 'process.report.getReport')** 

Here: ```@remotion/renderer/dist/compositor/get-executable-path.js:8:12```

Bun Version: 1.0.7
Node Version: 18.16.0
OS: Fedora Linux 38
Remotion version: 4.0.51

Since apparently the ```process.report``` obj. isn't available on Bun, I also tried to disable the ```isMusl``` func and running ```@remotion/compositor-linux-x64-gnu``` directly and that removed the error but the script never went to the end neither rendered out anything.

### PR DESCRIPTION
**Pull request by JonnyBurger**
Fixes #3062

### CODE REVIEW

**Comment by OmarKhled** [comment]
If possible, can you release it? I've a release dependent on it 😅
Thanks for your quick response!

**Comment by JonnyBurger** [comment]
I can later today!

**Comment by JonnyBurger** [comment]
@OmarKhled Out now, sorry it took another night!

**Comment by OmarKhled** [comment]
@JonnyBurger Thanks for the help! 
Just created a small fix at #3068 to check if process.report is undefined (the latest changes was checking if it's not undefined, though it's undefined in Bun) 
Would much appreciate it if you reviewed that and schedule another release as I'm still pending on that 😅

Thanks for your great contributions!

**Pull request merged**
