### PR TITLE
Add twoslash to docs & migrate contents

### LINKED ISSUE #447: Add twoslash to docs
[Issuehunt badges](https://issuehunt.io/r/JonnyBurger/remotion/issues/447)

This could be very cool for the docs

https://www.npmjs.com/package/docusaurus-preset-shiki-twoslash

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $162.00)

- [jonnyburger jonnyburger](https://issuehunt.io/u/jonnyburger) ($162.00)

### Submitted pull Requests
- [#465 fix(docs): complete docusaurus ts setup](https://issuehunt.io/r/remotion-dev/remotion/pull/465)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/JonnyBurger/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

### PR DESCRIPTION
**Pull request by frencojobs**
## This PR does
- [x] Add proper Twoslash integration
- [x] Make line highlighting work properly
- [x] Add support for top-level await in code blocks
- [x] Convert as much JSX API to TSX (done :tada:)
- [x] Modularize the examples with Twoslash include blocks
- [x] Handle imaginary imports with twoslash's multi-file system
- [x] Add copy button to code blocks
- ~Add syntax highlighting to type annotations?? (currently blocked by Twoslash)~

Closes #447 

## Help needed
- [x] `/parametrized-rendering` contains two code blocks that don't compile
- [x] `/ssr` contains a code blocks that don't import correct API
- [x] `Player API`'s first code block didn't complete all props so can't pass the compiler

## Remarks

- A few code blocks from API sections that only show type definitions and don't have bodies are excluded since they can't pass compiler to migrate
- `/composition`'s lazy import can't be correctly typed

### CODE REVIEW

**Comment by JonnyBurger** [comment]
Woah this is great! Thanks a lot for kicking this off! Don't worry if we cannot convert everything 100% to twoslash, if we can merge those examples who work great it's already a great improvement! We can strip the parts that are too hard for now.

Let me know if I should help! I will in any case in a few days try it out and see where we stand :)

**Comment by frencojobs** [comment]
Hi @JonnyBurger All docs except for what is mentioned in _my remark_ are migrated to twoslash code blocks. But two items mentioned in the _help needed_ are migratable but I couldn't get them right. Can you check them, please?

The first one is from `parametrized-rendering`,
```ts
import {Sequence} from 'remotion';
import {MyComponent} from './MyComponent';

export const Root = () => {
  return (
    <>
      <Sequence
        id="my-video"
        width={1080}
        height={1080}
        fps={30}
        component={MyComponent}
        defaultProps={{
          propOne: 'Hi',
          propTwo: 10
        }}
      />
    </>
  )
}
```

TSC is complaining that `Sequence` doesn't have these `id`, `width`, `height` etc props. Is that correct? Did you mistake it with composition? (I'm not sure about remotion APIs)

The second one is from `ssr` and TSC says this import doesn't exist.
```ts
import {evaluateRootForCompositions} from 'remotion';
```

We can leave them not migrated if TSC is wrong but can you check and confirm, please. Thanks!

**Comment by Iamshankhadeep** [comment]
> ```ts
> import {Sequence} from 'remotion';
> import {MyComponent} from './MyComponent';
> 
> export const Root = () => {
>   return (
>     <>
>       <Sequence
>         id="my-video"
>         width={1080}
>         height={1080}
>         fps={30}
>         component={MyComponent}
>         defaultProps={{
>           propOne: 'Hi',
>           propTwo: 10
>         }}
>       />
>     </>
>   )
> }
> ```

This should be `<Composition/>` I suppose as `<Sequence />` does not have this props. @JonnyBurger 

> ```ts
> import {evaluateRootForCompositions} from 'remotion';
> ```

we don't have `evaluateRootForCompositions` this in our codebase. I checked just now.

**Comment by JonnyBurger** [comment]
I just fixed the remaining snippets!
And I got to play around with it for the first time, this is absolutely brilliant!

Not only is it helpful for the reader, but it also ensures that we don't have typoes or unrunnable code in our documentation! I never knew we could have a type checker for our docs - now I never wanna go back! :)

For me it's good enough to merge, we can have e.g. the copy button in another PR. But I'll wait for you to have the final go!

**Comment by frencojobs** [comment]
Great! I have added exact copies of the default copy to clipboard buttons. I'll open this up to ready for review.

Sorry for delay, timezones you know. By the way, I'm not sure about how these Issuehunt stuffs work.

**Comment by frencojobs** [comment]
OOMs on `docusaurus build`. We might have to wait for https://github.com/facebook/docusaurus/pull/4997. I'm looking for a workaround in the meantime.

**Comment by frencojobs** [comment]
Seems like trying to increase the memory only results in _"rewarding for bad behavior"_ for this RAM eater. Since this is only because of the way docusaurus handle things (can confirm this, transforming the same files in eleventy which uses the same remark plugin only takes a portion of the time it took in docusaurus), I'll try to switch to another approach by twoslashifying markdown files beforehand feeding to docusaurus.

**Comment by JonnyBurger** [comment]
I saw it too, performance is very poor too. Let's consider opening a (proper) issue on shiki-twoslash-docusaurus, maybe we can get some help from there too!

**Comment by JonnyBurger** [comment]
That's pretty clever! Thanks for pushing it further. Let's see if it works 🤔 

If the CI fails with `cb()` not called, often it can be fixed by just retrying. Unsure why npm is shaky.

**Comment by frencojobs** [comment]
@JonnyBurger Haha, sorry didn't use that technique aforementioned. I tried it for a day and gave up since mdx parser can't seem to be parsing stuffs correctly. But today I found a leak in twoslash and fixed it. It's soo much faster now than before. It is merely about the same performance as the normal docusaurus (at least on my end). Still waiting for the checks but I'm sure they'll pass. So it is mergeable now.

Also, because I wanted to make sure first, I added a script called `format` in the docs' script folder. I noticed that prettier can't format tsx/ts code blocks in markdown, and there are some inconsistencies in the code blocks such as tabs, semicolons etc, the script will help format the code.

It would be nice if you could review it too. If you think it's good, you can format the files yourself, it should work fine but will probably require some manual checks as to update line highlights etc.

Thanks.

**Review by JonnyBurger — APPROVED** [review]
This is so great! Absolutely flashed by the PR, there are so many nice details, bugs found, done with so much care! I'm in love with this PR... 🥰

Thanks a lot for making this, and going all the way, even finding and solving a bug in shikijs - incredible work!

**Pull request merged**
