### PR TITLE
make default-props codemod ast-based

### LINKED ISSUE #4422: Convert "Update default props" to a Recast codemod.
We currently have a bug when saving the default props, I made a fixture in https://github.com/remotion-dev/remotion/tree/fix-save-default-props and the bug is also described in the Discord issue below.

We have 2 types of codemods:

- AST-based codemods, like https://github.com/remotion-dev/remotion/blob/40e627bc781bb42b94fb3db577c3b5544a269e6d/packages/studio-server/src/codemods/duplicate-composition.ts#L32 a
- Dumb codemods, which parse the file without walking the AST tree, like https://github.com/remotion-dev/remotion/blob/40e627bc781bb42b94fb3db577c3b5544a269e6d/packages/studio-server/src/codemods/update-default-props.ts#L1-L177

We have a feature in the Remotion Studio (How to run the Studio: https://www.remotion.dev/docs/contributing/#running-the-cli) where you change the data interactively and then save it back to the Root.tsx file.

We should convert the "update default props" codemod (shown above) from a dumb codemod to a AST-based codemod using the "recast" module to fix issues like the one below.

There are tests like https://github.com/remotion-dev/remotion/blob/40e627bc781bb42b94fb3db577c3b5544a269e6d/packages/studio-server/src/test/update-default-props.test.ts#L1 which should still pass of course. The fixture that was posted should above should also be fixed.

💎 This issue has a bounty on it!

Read our contributing guidelines: 
- **How to contribute**: https://www.remotion.dev/docs/contributing/
- **Implementing a new feature**: https://www.remotion.dev/docs/contributing/feature
- **Implementing a new option**: https://www.remotion.dev/docs/contributing/option
- **Write documentation**: https://www.remotion.dev/docs/contributing/docs
- **Bounty information**: https://www.remotion.dev/docs/contributing/bounty

/bounty 140

---

[From message posted on Discord by **thecmdrunner**](https://discord.com/channels/809501355504959528/1297882362197315664/1298240452016869376)
----
That's right, it doesn't let me save when I have two compositions that use the const props object.

But when I add another composition in between, with inline default props, I could reproduce the behavior.

Here's a stackblitz, try editing the props for `HelloWorld` and saving it, then you'll see the `Placeholder` composition disappear from Root.tsx and the left panel for Compositions.
https://stackblitz.com/edit/remotion-dev-template-helloworld-btxf5e?file=src/Root.tsx

### PR DESCRIPTION
**Pull request by hunxjunedo**
/claim #4422 
closes #4422 

image

https://github.com/user-attachments/assets/589584f3-bf6a-4c3e-a9ef-fa51eccc3ed1

https://github.com/user-attachments/assets/cc44a7a1-31b7-460c-96c3-7df0906aad85

@JonnyBurger please feel free to request any changes required, not just for the sake of completion of this issue, but also for feedback on my work.

### CODE REVIEW

**Comment by hunxjunedo** [comment]
looks like there's the need of extra code to handle dates out of the box, let me have a look

**Comment by JonnyBurger** [comment]
Thanks for dealing with the tests, please ping me if it is ready to review!

**Comment by hunxjunedo** [comment]
@JonnyBurger the PR is ready for review, 2 checks are failing, which is strange and don't seem to be caused by this PR.

**Comment by JonnyBurger** [comment]
Thanks! Works great 🥳

**Pull request merged**
