### PR TITLE
add template-empty to the template list

### PR DESCRIPTION
**Pull request by aneeshrelan**
Implements #616

### CODE REVIEW

**Comment by aneeshrelan** [comment]
@Iamshankhadeep @JonnyBurger I might need some help in transferring the repository. A simple transfer throws a permission error. The template is available at: [template-empty](https://github.com/aneeshrelan/template-empty) if you want to take a look and provide feedback

**Comment by JonnyBurger** [comment]
Thanks a lot! It looks 90% done :D Just a few requests:

- We don't commit the lockfile to the templates, so it works with npm and yarn, so for this reason please remove `package-lock.json`.
- Can you also remove `express`, `@types/express` dependencies as well as `Dockerfile` and `.dockerignore`. (this is the minimalistic template)
- In `.github/workflows/render-video.yml` the two inputs should be removed as well, it's only used in the Hello World

Otherwise perfect! What permission error do you get when transferring the repo?

**Comment by aneeshrelan** [comment]
Thank you for the feedback. Resolved all, please check :D

For the error, when I click on the "Transfer ownership" in the repo settings and mention the `remotion-dev` organisation. It throws an error saying "You don’t have the permission to create public repositories on remotion-dev". I might be missing something

**Comment by JonnyBurger** [comment]
@aneeshrelan Ah ok, probably a GitHub thing. In that case, transfer it to `JonnyBurger` and then I'll transfer it again!

**Comment by aneeshrelan** [comment]
@JonnyBurger Transferred. Please check

**Review by JonnyBurger — APPROVED** [review]
Thanks a lot! 🙌🏼

**Pull request merged**
