### PR TITLE
Fix some misspelled function/module names

### PR DESCRIPTION
**Pull request by akx**

### CODE REVIEW

**Comment by akx** [comment]
Test failures seem unrelated to these changes.

**Comment by JonnyBurger** [comment]
Thanks a lot! 🙌  Did you use a specific tool to spot these spelling errors?

**Comment by akx** [comment]
@JonnyBurger Not really. Well, a highly evolved wetware neural network along with a pair of optical acquisition devices (that do need some external calibration)... 🤓

**Comment by JonnyBurger** [comment]
@akx Absolutely amazed by todays technology!

**Pull request merged**
