### PR TITLE
Support Fullscreen in Remotion Studio

### LINKED ISSUE #2523: Fullscreen button in Studio
In the Remotion Player, we have a fullscreen button.

Can we also add one in the Studio? Mockup:

image

Fulfillment Criteria:

- Should only show if the browser supports fullscreen
- Should fullscreen the canvas element, and size the video correctly that it takes the biggest space it can, but not stretch or go beyond the edges (standard video behavior)
- Keyboard shortcuts should remain functional, probably no change is required for this.

💎 This issue has a bounty on it!

Read our contributing guidelines: 
- **How to contribute**: https://www.remotion.dev/docs/contributing/
- **Implementing a new feature**: https://www.remotion.dev/docs/contributing/feature
- **Implementing a new option**: https://www.remotion.dev/docs/contributing/option
- **Write documentation**: https://www.remotion.dev/docs/contributing/docs
- **Bounty information**: https://www.remotion.dev/docs/contributing/bounty

/bounty 100

### PR DESCRIPTION
**Pull request by tobihans**
This PR adds fullscreen preview capability to Remotion Studio.

Closes #2523.
/claim #2523

### CODE REVIEW

**Comment by JonnyBurger** [comment]
Thanks a lot for the PR!
Once it's ready, just let me know and we'll review it.

No rush there as I will only get to it on Monday at earliest.

**Comment by tobihans** [comment]
That's noted. Thank you

**Review by JonnyBurger — DISMISSED** [review]
Just excellent! Very clean.

Thanks a lot for this nice first contribution and for your patience 🙌 💙

**Review by JonnyBurger — APPROVED** [review]

**Comment by tobihans** [comment]
Thank you too, for giving me the opportunity to contribute :)

**Pull request merged**
