### PR TITLE
chore: add function signature params in JSDoc pattern to APIs

### PR DESCRIPTION
**Pull request by kaf-lamed-beyt**
Hi @JonnyBurger, this is still a work in progress. Please take a look, and let me know if I'm on the right track.

### CODE REVIEW

**Comment by kaf-lamed-beyt** [comment]
I also just noticed now that I used my other github account to make the first commit 😪. 

So I switched it to my original account, hence the "minor" commit message

**Comment by JonnyBurger** [comment]
@kaf-lamed-beyt Looks perfect so far 🙌🏼

**Comment by kaf-lamed-beyt** [comment]
One update @JonnyBurger,

Whenever I come across comments like this 👇🏼 , without the `@description` I've proceeded by adding them. I hope that is fine 

image

**Comment by JonnyBurger** [comment]
Absolutely, this is the 🍒 on the top!

**Comment by kaf-lamed-beyt** [comment]
Aye! Noted. 😎

**Comment by kaf-lamed-beyt** [comment]
Hi @JonnyBurger,

I've added all the required @description keywords, where necessary. Please, take a look, thanks!

**Comment by JonnyBurger** [comment]
Thank for all that hard work! 🙌
That's amazing and will improve the developer experience quite a bit!

If you are up for it, I am happy to add a $100 bounty to this issue retroactively that you can claim via Algolia!

**Comment by kaf-lamed-beyt** [comment]
I am glad that I could help.

...and yes, I'd definitely love the bounty! 😃

Thank you so much again, for the opportunity! I'm heading to pick another issue that I'd love to work on

**Pull request merged**
