### PR TITLE
chore(docs): add ec2 docker gpu instructions

### PR DESCRIPTION
**Pull request by kaf-lamed-beyt**
addresses #3087 
How does this look @JonnyBurger?

### CODE REVIEW

**Comment by JonnyBurger** [comment]
Appreciate you a lot @kaf-lamed-beyt! I still need to test if these instructions work, then I'll merge it!

**Comment by kaf-lamed-beyt** [comment]
That sounds good @JonnyBurger. No problem!

**Comment by JonnyBurger** [comment]
@kaf-lamed-beyt It works! Thanks a lot for sending this! Added you as a credit too on the page

**Comment by kaf-lamed-beyt** [comment]
Ayy! Thanks a lot, @JonnyBurger! I appreciate it.

**Pull request merged**
