### PR TITLE
`@remotion/lambda`: Retry if Lambda got ECONNRESET exception

### PR DESCRIPTION
**Pull request by JonnyBurger**
https://discord.com/channels/809501355504959528/844143007183667220/1290675917106184265

### CODE REVIEW

**Comment by AymaBA** [comment]
I have this error on the 4.0.223 

```json
 [
{
"chunk": null,
"frame": null,
"name": "Error",
"stack": "Error: Error: aborted\n    at connResetException (node:internal/errors:718:14)\n    at TLSSocket.socketCloseListener (node:_http_client:456:19)\n    at TLSSocket.emit (node:events:525:35)\n    at node:net:320:12\n    at TCP.done (node:_tls_wrap:588:7)\n    at streamRendererFunctionWithRetry (/var/task/index.js:109760:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /var/task/index.js:110119:7\n    at async Promise.all (index 5)\n    at async innerLaunchHandler (/var/task/index.js:110117:3)\n    at async launchHandler (/var/task/index.js:110300:28)\n    at async innerHandler (/var/task/index.js:112132:22)\n    at async innerRoutine (/var/task/index.js:112254:5)\n    at async Runtime.handleOnceStreaming (file:///var/runtime/index.mjs:1118:26)",
"type": "stitcher",
"isFatal": true,
"tmpDir": null,
"attempt": 1,
"totalAttempts": 1,
"willRetry": false,
"message": "Error: aborted\n    at connResetException (node:internal/errors:718:14)\n    at TLSSocket.socketCloseListener (node:_http_client:456:19)\n    at TLSSocket.emit (node:events:525:35)\n    at node:net:320:12\n    at TCP.done (node:_tls_wrap:588:7)"
}]
```

**Comment by JonnyBurger** [comment]
@AymaBA No nevermind, it is actually fixed by #4347!

Will be fixed in next version

**Comment by NathanDjianMartin** [comment]
When you say it will be fixed in the next version does it mean that it is fixed in 4.0.225?

**Comment by JonnyBurger** [comment]
@NathanDjianMartin Correct!

**Pull request merged**
