### PR TITLE
[V3] Multi browser instance and Parallel Encoding mode

### PR DESCRIPTION
**Pull request by yuyuyzl**
PR for #584.

```js
/**
 * Set the concurrent mode.
 * Pass in 'tab' and the renderer will launch a single browser and pages will be opened in multiple tabs.
 * Pass in 'browser' and the renderer will launch multiple browsers and open one page in each browser.
 * Use 'browser' to maximize CPU utilization and render faster.
 */
setConcurrentMode,

/**
 * Enabling parallel encoding means render frames and encode video at the same time.
 * The image will be passed directly into ffmpeg.
 */
setParallelEncoding,
```

Test passed.

TODO: documentation

### CODE REVIEW

**Comment by JonnyBurger** [comment]
Thanks a lot for this brilliant PR! 💙 
This is a great improvement, and can't wait to test and ship it.

We plan to add this for the next major release (3.0) alongside Lambda, which will allow for a refactor in the rendering pipeline. So we need a bit of time to get it merged, regardless of it, we plan to ship it.

**Comment by iamkhalidbashir** [comment]
When will this be merged @yuyuyzl  @JonnyBurger 

This is very much required!

I have tried to install using https://gitpkg.vercel.app/ but wasn't able to ;/

**Comment by iamkhalidbashir** [comment]
@yuyuyzl  You are the hero man
Just rendered 
And time reduced from 35 seconds to 12 seconds <3

So happy <3 <3

btw setting the parallelism to os.cpus().length will make throws this warning and hangs the CPU
So using parallelism null renders it perfect though curious what the optimal value for parallelism

Screenshot from 2021-09-25 18-39-16


Also `parallelEncoding: true` dosent work as it throws this error

Screenshot from 2021-09-25 18-44-29

**Comment by JonnyBurger** [comment]
@iamkhalidbashir We want to merge this as a part of the next major release, so it will take at least 1 to 2 months from now until the release.

For your convienience, I published the state of this PR to NPM: "2.4.0-alpha.b886f9bc".
See https://remotion.dev/docs/prereleases for how to install this version.

**Comment by iamkhalidbashir** [comment]
> @iamkhalidbashir We want to merge this as a part of the next major release, so it will take at least 1 to 2 months from now until the release.
> 
> For your convienience, I published the state of this PR to NPM: "2.4.0-alpha.b886f9bc".
> See https://remotion.dev/docs/prereleases?version=2.4.0-alpha.b886f9bc for how to install this version.

That's awesome thank you

**Comment by yuyuyzl** [comment]
> Also `parallelEncoding: true` dosent work as it throws this error
> 
> as we dont get the pre encode file at location: preEncodedFileLocation

seems u have edited out the image, is the exception still there?
the parallel encoding mode will create a stitcher(ffmpeg) before render starts, and render a video instead of image sequence inside the temp folder, and it will be deleted after the rendering process. In the original mode, the images rendered in temp folder will be deleted as well.
so, if you want to locate the `preEncodedFileLocation` temp folder, you should clone the repo and remove the cleanup function call yourself.

**Comment by iamkhalidbashir** [comment]
> > Also `parallelEncoding: true` dosent work as it throws this error
> > as we dont get the pre encode file at location: preEncodedFileLocation
> 
> seems u have edited out the image, is the exception still there? the parallel encoding mode will create a stitcher(ffmpeg) before render starts, and render a video instead of image sequence inside the temp folder, and it will be deleted after the rendering process. In the original mode, the images rendered in temp folder will be deleted as well. so, if you want to locate the `preEncodedFileLocation` temp folder, you should clone the repo and remove the cleanup function call yourself.

Thanks @yuyuyzl 
Although I figured it later :)

Can you export `getAssetsData` function https://github.com/remotion-dev/remotion/blob/b886f9bc342940aeea16abbabe390e867f492ab6/packages/renderer/src/stitcher.ts#L50

**Comment by JonnyBurger** [comment]
I'm merging the parallel encoding feature in the v3 branch and enabling it by default!
Also coming back to the multi-render feature within the next few days, stay tuned.

**Pull request merged**
