### PR TITLE
Rust video metadata

### PR DESCRIPTION
**Pull request by alexfernandez803**
Possible fix for. 
https://github.com/remotion-dev/remotion/issues/2430

### CODE REVIEW

**Comment by alexfernandez803** [comment]
@JonnyBurger have I implemented it in correct places? This one need a documentation as well?

**Comment by JonnyBurger** [comment]
Very nice!

Two changes requested:

- Can we close compositor with `finishCommands` and `waitForDone`?
- Can we make it a public API and add a documentation page in `@remotion/renderer` section?

**Comment by alexfernandez803** [comment]
> Very nice!
> 
> Two changes requested:
> 
> * Can we close compositor with `finishCommands` and `waitForDone`?
> * Can we make it a public API and add a documentation page in `@remotion/renderer` section?

Noted.. Let me figure those things first. Will do the documentation after.

**Comment by JonnyBurger** [comment]
Awesome! Will need some time to review it, hopefully I can do it this week still.

**Comment by JonnyBurger** [comment]
Stellar! ⭐ 

Excellent job @alexfernandez803, thanks for this feature and sorry for the long wait!

**Review by JonnyBurger — DISMISSED** [review]

**Comment by JonnyBurger** [comment]
You can collect the bounty by contacting @MehmetAdemi!

**Review by JonnyBurger — APPROVED** [review]

**Pull request merged**
