### PR TITLE
feat: render video to out folder

### PR DESCRIPTION
**Pull request by ahmadrosid**
## Description
Fixes https://github.com/remotion-dev/remotion/issues/518

## How to test?
- Build package
```bash
npm run build
```
- Go to example folder
```bash
cd packages/example
```
- Run render
```bash
../cli/remotion-cli.js render src/index.tsx react-svg video.mp4
```
- Render at sub folder
```bash
../cli/remotion-cli.js render src/index.tsx react-svg nested/video.mp4
```

### CODE REVIEW

**Review by JonnyBurger — CHANGES_REQUESTED** [review]
Thanks! This is a great start to make the folder if it doesn't exist, but the idea is to not always put it in an out folder, only by default.

So the hardcoded out path should be reverted, and instead the templates should be updated. See the acceptance criteria of the original issue again and let me know when you have questions!

**Comment by ahmadrosid** [comment]
> Thanks! This is a great start to make the folder if it doesn't exist, but the idea is to not always put it in an out folder, only by default.
> 
> So the hardcoded out path should be reverted, and instead the templates should be updated. See the acceptance criteria of the original issue again and let me know when you have questions!

Sure @JonnyBurger updated, do we need to changes the example render from
```bash
remotion render src/index.tsx react-svg video.mp4
```
To
```bash
remotion render src/index.tsx react-svg out/video.mp4
```

**Comment by JonnyBurger** [comment]
@ahmadrosid Yes would be nice, but most importantly a PR to each of the templates 😊

**Comment by ahmadrosid** [comment]
> @ahmadrosid Yes would be nice, but most importantly a PR to each of the templates 😊

Here's PR to the templates @JonnyBurger 
- https://github.com/remotion-dev/template-helloworld/pull/4
- https://github.com/remotion-dev/template-three/pull/1

**Comment by JonnyBurger** [comment]
Thanks! Almost there, what about the templates for plain JS, Still and Text-To-Speech?

**Comment by JonnyBurger** [comment]
We also just merged a new template, `remotion-dev/template-empty` which would be nice!

**Comment by ahmadrosid** [comment]
@JonnyBurger  Sure let me add more PR to templates for plain JS and remotion-dev/template-empty.

For the template-still is already have that build folder I believe.
- https://github.com/remotion-dev/template-still/blob/main/package.json#L8
- https://github.com/remotion-dev/template-still/blob/main/.gitignore#L6

And I can't find repo for this template `Text-To-Speech`.

**Comment by ahmadrosid** [comment]
New PRs here:
- https://github.com/remotion-dev/template-helloworld-javascript/pull/3
- https://github.com/remotion-dev/template-empty/pull/1

**Review by JonnyBurger — APPROVED** [review]

**Review by JonnyBurger — APPROVED** [review]

**Comment by JonnyBurger** [comment]
All shipped! Thanks a lot @ahmadrosid! 🎉

**Pull request merged**
