### PR TITLE
Added compatibleOnly flag

### PR DESCRIPTION
**Pull request by Ritish134**
issue #3920 

Added compatibleOnly flag to `packages/lambda/src/cli/args.ts` and `packages/lambda/src/cli/commands/functions/ls.ts`,

Further Could you guide me where I could update the docs for this issue 

/claim 3920

### CODE REVIEW

**Comment by Ritish134** [comment]
It seems like the pull request might require further changes to ensure the changes are implemented correctly. Your feedback and assistance would be greatly appreciated to help finalize this update.

Thanks!

**Comment by JonnyBurger** [comment]
> It seems like the pull request might require further changes to ensure the changes are implemented correctly. Your feedback and assistance would be greatly appreciated to help finalize this update.
> 
> Thanks!

ChatGPT? 😝

**Review by JonnyBurger — DISMISSED** [review]

**Comment by Ritish134** [comment]
@JonnyBurger Please review it once

**Comment by JonnyBurger** [comment]
Thanks!

**Pull request merged**
