### PR TITLE
playbackRate prop to the <Gif> component added

### LINKED ISSUE #2942: Add a `playbackRate` prop to the <Gif> component
Could just divide the current frame with the `playbackRate` to make the GIF play faster or slower.

And then document the new prop in gif.md!

### PR DESCRIPTION
**Pull request by anikdhabal**
fixes #2942 
/claim #2942

### CODE REVIEW

**Comment by JonnyBurger** [comment]
Thanks! 

How come that you, @hitesh-sihara and @Vishal-Sikka have all wrote the same documentation? 😂 ChatGPT much?

**Comment by JonnyBurger** [comment]
Thanks for the contribution! 🙌🏼 Merging

Gripe: It didn't actually work as expected and described. 0.5 would make the Gif play twice as fast, and 2 twice as slow. Actually testing it would have revealed this.

**Comment by Hitesh-sisara** [comment]
> Thanks!
> 
> How come that you, @hitesh-sihara and @Vishal-Sikka have all wrote the same documentation? 😂 ChatGPT much?

 @Vishal-Sikka's doc looked good so i copied from his pr 😂, maybe @anikdhabal did the same

**Comment by anikdhabal** [comment]
> > Thanks!
> > How come that you, @hitesh-sihara and @Vishal-Sikka have all wrote the same documentation? 😂 ChatGPT much?
> 
> @Vishal-Sikka's doc looked good so i copied from his pr 😂, maybe @anikdhabal did the same

Yes I also doing the same thing😂.I don't think there is anything extra we need to add apart from that.

**Pull request merged**
