### PR TITLE
fix:  template button behaving as link 

### PR DESCRIPTION
**Pull request by harshbisle**
Fixes:

Home page: "Find a template" button doesn't appear as button but as link #2029

### CODE REVIEW

**Comment by JonnyBurger** [comment]
Hmm, I kinda disagree with this 😕

Links are better right? Since you can for example right-click and press "Open new tab".
Or it works without JavaScript.

Am I missing a benefit of doing this?

**Comment by harshbisle** [comment]
Totally! I agree that links are better. But we can also right-click and open a new tab using the button. 

Here the PR is just tackling the issue of the Template button rendering as a link occasionally. 

If not, how would you suggest doing it?

**Comment by JonnyBurger** [comment]
I see the problem now! Thanks, will review it soon.

**Comment by JonnyBurger** [comment]
Ok, I reverted it now to a link to keep it an <a> tag but kept the fix otherwise. Thanks a lot for the polish! 😃🙌🏼

**Comment by harshbisle** [comment]
Awesome!

**Pull request merged**
