### PR TITLE
Report slowest frames

### LINKED ISSUE #1344: Report slowest frames of renderMedia()
[Issuehunt badges](https://issuehunt.io/r/remotion-dev/remotion/issues/1344)

**🎃 This issue is part of our Hacktoberfest campaign!**
📚 [Read more about Hacktoberfest here](https://remotion.dev/hacktoberfest)
🕛 This issue is currently assigned to @uragirii!

There is already a function for finding the slowest chunks inside renderMediaOnLambda(), but it would be useful to measure each single frame in renderMedia() and return the slowest frames so one can optimize the render times of it.

Acceptance criteria:

- Measure the time for each frame and store it in-memory, e.g. in a JavaScript object
- Make sure to free up the memory afterwards to not create a memory leak
- Make `renderMedia()` return an object of which one of the properties is `slowestFrames`, which returns the 10 slowest frames (if there are any)
- In the `cli` package, grab that information, and print the slowest frames using `Log.verbose`
- In the `lambda` package, in `renderer.ts`, log the slowest frames as well.
- Add documentation to `render-media.md` describing the feature and mention the version it's going to be available in (current version + 0.0.1)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $167.00)

- [jonnyburger jonnyburger](https://issuehunt.io/u/jonnyburger) ($167.00)

### Submitted pull Requests
- [#1381 Report slowest frames](https://issuehunt.io/r/remotion-dev/remotion/pull/1381)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/remotion-dev/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

### PR DESCRIPTION
**Pull request by uragirii**
Fixes #1344 

`renderMedia` returns array of 10 slowest frames with frame indexes for user to optimise them. 

Tasks: 
- [x] Report in cli in verbose mode
- [x] Log slowest frames in lambda
- [x] Update docs
- [x] CI build pass (or fix tests)?

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#1344: Report slowest frames of renderMedia()](https://issuehunt.io/repos/274495425/issues/1344)
---
</details>

### CODE REVIEW

**Comment by uragirii** [comment]
Screenshot 2022-10-08 at 8 13 14 PM
@JonnyBurger idk if its a configuration error? or older node version

**Comment by JonnyBurger** [comment]
@uragirii `Array.at` cannot be used because it is not supported in Node.JS. We need to use normal `array[i]` notation for now

**Comment by uragirii** [comment]
@JonnyBurger should be ready for review

**Comment by uragirii** [comment]
@JonnyBurger now it should be fixed. Also, there is a small "bug", the first `concurrent` number of frames would always be in the slowest frames as they also include the time of opening chrome tabs. We _could_ get "actual" concurrency value and omit them, what do you think?

**Comment by JonnyBurger** [comment]
@uragirii Thanks!

I have noticed another bug: The timing is since the last frame was rendered, but since multiple frames are rendered in parallel, that does not reflect the time it has taken to render a frame. Fixed now!

Regarding the first frame of a tab being slower, I think let's embrace it! It's useful to see the initialization time. This looks insightful to me:

image

**Review by JonnyBurger — APPROVED** [review]
And with that, fully happy 🎉

Thanks a lot for building this feature! How long did you approximately spend on this PR?

**Comment by uragirii** [comment]
>The timing is since the last frame was rendered, but since multiple frames are rendered in parallel, that does not reflect the time it has taken to render a frame. 

As didn't thought of that! Great!

>How long did you approximately spend on this PR?

1-1.5 hour

**Pull request merged**
