### PR TITLE
Fixed:  buttons non clickablity #1985

### PR DESCRIPTION
**Pull request by harshbisle**
Solves: Website buttons cannot be clicked between 545px and 700px viewport #1985

/claim #1985

My first PR to remotion 🎉 🎊

### CODE REVIEW

**Comment by JonnyBurger** [comment]
Thanks a lot! 🙌

**Comment by harshbisle** [comment]
Thank you so much for merging my contribution! Can you please provide a heads-up on the next steps? Looking forward to continuing my contributions to Remotion.

**Comment by JonnyBurger** [comment]
Hi @harshbisle, awesome! 🙌

I don't really have another issue at hand right now. They pop up from time to time though and we are also happy if you report more valid issues!

**Comment by harshbisle** [comment]
Hey @JonnyBurger , No problem. I think I have found some more quick fixes to be done on the landing page. I will definitely let you know on the discord server. Thanks 😊

**Pull request merged**
